### ISSUE TITLE
Allow for IP address ingress

### ISSUE THREAD

**Issue by 2br-2b** [otwld/ollama-helm#134]
### Is your feature request related to a problem? Please describe

Right now, I don't see any way to allow ingress via an IP address. It would be helpful if I could allow Ollama to be accessed at an IP address

### Describe the solution you'd like

Allow ingress at the IP address (I don't know if this is the best way to do this):

```yaml
# Configure the ingress resource that allows you to access the
ingress:
  # -- Enable ingress controller resource
  enabled: false

  # -- IngressClass that will be used to implement the Ingress (Kubernetes 1.18+)
  className: ""

  # -- Additional annotations for the Ingress resource.
  annotations: {}
    # kubernetes.io/ingress.class: traefik
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

  # The list of hostnames to be covered with this ingress record.
  hosts:
    - host: ollama.local
      paths:
        - path: /
          pathType: Prefix

    - ip-addr: 192.168.1.226
      paths:
        - path: /
          pathType: Prefix
```

### Additional context

```markdown

```

**Comment by jdetroyes** [comment]
Hello @2br-2b,

The ingress is not designed for this kind of usage, [from documentation](https://kubernetes.io/docs/concepts/services-networking/ingress/):
> Make your HTTP (or HTTPS) network service available using a protocol-aware configuration mechanism, that understands web concepts like URIs, hostnames, paths, and more. The Ingress concept lets you map traffic to different backends based on rules you define via the Kubernetes API.

If want to expose Ollama service directly from IP, you can configure the service as a LoadBalancer :

```yaml

# Configure Service
service:

  # -- Service type
  type: LoadBalancer

  # -- Service port
  port: 11434

  # -- Load Balancer IP address, not necessary but you can uncomment is needed (loadBalancerIP is deprecated in 1.24) 
  # loadBalancerIP: 192.168.1.226 

  # -- Annotations to add to the service
  annotations: {}
```

Ollama should be available at http://192.168.1.226:11434/
