### ISSUE TITLE
Create model option

### ISSUE THREAD

**Issue by olegsmetanin** [otwld/ollama-helm#135]
### Is your feature request related to a problem? Please describe

The following options are available for setting the context size:
1) ollama run / set parameter num_ctx 4096 [link](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-specify-the-context-window-size)
2) specify the num_ctx parameter in Ollama API [REST API](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-specify-the-context-window-size)
3) [Modelfile](https://github.com/ollama/ollama/blob/main/docs/modelfile.md#basic-modelfile)
Right now there is no ability to set context size on chart deployment phase.
 

### Describe the solution you'd like

Extend ollama.model node to support create array:
```
ollama:
  models:
    pull:
      - llama3.1
    create:
      - name: llama3.1-ctx32768
        model: |
          FROM llama3.1
          PARAMETER num_ctx 32768
    run:
      - llama3.1
      - llama3.1-ctx32768
```
Render something like
```
cat <<EOF > $HOME/.ollama/models/{.name}
{.model}
EOF
ollama create {.name} -f $HOME/.ollama/models/{.name}
```
[before ollama.models.run section rendering](https://github.com/otwld/ollama-helm/blob/main/templates/deployment.yaml#L162)

Deployment:
```
helm upgrade ollama ollama-helm/ollama \
  --install --create-namespace -n ollama --version 1.4.0 \
  --set ollama.models.pull[0]=llama3.1 \
  --set ollama.models.create[0].name=llama3.1-ctx32768 \
  --set ollama.models.create[0].model="FROM llama3.1\nPARAMETER num_ctx 32768" \
  --set ollama.models.run[0]=llama3.1-ctx32768
```

### Describe alternatives you've considered

ConfigMaps, but Modelfiles are usually short, we can live without Configmaps here

### Additional context

```markdown

```
