### ISSUE TITLE
Add `extraObjects` in values.yaml

### ISSUE THREAD

**Issue by jlandowner** [otwld/ollama-helm#136]
### Is your feature request related to a problem? Please describe

I am running ollama on Amazon EKS and use Amazon EFS as a model volume.

aws-efs-csi-driver supports a dynamic provisioning but it is not available in some use cases e.g. use [existing EFS filesystem](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/examples/kubernetes/multiple_pods) and [volume_path](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/examples/kubernetes/volume_path).

In these usecase, we have to create PersistentVolume and StorageClass manually.

Also, sometimes we need NetworkPolicy, PriorityClass and so on.

### Describe the solution you'd like

Add `extraObjects` in values and support to apply any extra kubernertes resources in the same lifecycle of the chart.

```yaml:values.yaml
extraObjects:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: efs-pv1
  spec:
    capacity:
      storage: 50Gi
    volumeMode: Filesystem
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: efs-sc
    mountOptions:
      - tls
    csi:
      driver: efs.csi.aws.com
      volumeHandle: fs-e8a95a42:/dir1
```

### Additional context

```markdown
There are lots of projects that implement `extraObjects` in the values.yaml.
e.g.
- https://github.com/cert-manager/cert-manager/pull/6424
- https://github.com/kubernetes/autoscaler/pull/7243
- https://github.com/traefik/traefik-helm-chart/pull/643
```
