### ISSUE TITLE
No Pod Deployed on Kubernetes.

### ISSUE THREAD

**Issue by Greeley** [otwld/ollama-helm#15]
K8S Info:
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.26.1

I copied the default values an added a service account name, and added the mistral model.

When I use the helm install command it creates the namespace, deployment, and secrets but no pod, jobs, or persistent volume.

I have GPU disabled as my cluster doesn't have any GPUs right now, but it will soon.

Is there something I'm missing? When I first tried to use it I had to create the namespace first as helm wouldn't do it.

This is also my first time using helm, I created yaml files to do it using kubectl but encountered the same issue, deployment but no active pods.

**Comment by jdetroyes** [comment]
Hello @Greeley 

- Helm do not create namespace automatically if it doesn't exist in your cluster, you can pass the `--create-namespace` flag when you run `helm install`
-  For using persistant volume, you need a Persistant Volume Claim, you can set up a provisioner and use `storageClass` or create manually and use `existingClaim`, otherwise data will be deleted when container ends.

For the pod, what is the status of the ollama helm deployment (`helm status --namespace <namespace> <name>`) and the describe of the kubernetes deployment(`kubectl describe -n <namespace> <deployment ressource>`) ?

**Comment by Yabbo** [comment]
where should we be mapping persistent volume claims?

**Comment by jdetroyes** [comment]
- If you have defined manual PVC, you can set the PVC name:
```yaml
persistentVolume:
# -- Enable persistence using PVC
  enabled: true
# -- If you'd like to bring your own PVC for persisting Ollama state, pass the name of the
  # created + ready PVC here. If set, this Chart will not create the default PVC.
  # Requires server.persistentVolume.enabled: true
  existingClaim: ""
```

- If you have a dynamic provisioner in your cluster, you can just set the provisioner's class or leave blank if one storage class is set as default:
```yaml
persistentVolume:
# -- Enable persistence using PVC
  enabled: true
# -- Ollama server data Persistent Volume Storage Class
  # If defined, storageClassName: <storageClass>
  # If set to "-", storageClassName: "", which disables dynamic provisioning
  # If undefined (the default) or set to null, no storageClassName spec is
  # set, choosing the default provisioner.  (gp2 on AWS, standard on
  # GKE, AWS & OpenStack)
  storageClass: ""
```

**Comment by Yabbo** [comment]
my question was what directories as we mapping with the PVC.

**Comment by jdetroyes** [comment]
It's `/root/.ollama` as in the [deployment.yaml:](https://github.com/otwld/ollama-helm/blob/main/templates/deployment.yaml)

```yaml
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
```
