### ISSUE TITLE
pod fails to start with amd option

### ISSUE THREAD

**Issue by nopunYntendeed** [otwld/ollama-helm#150]
### What happened?

Hi, thanks for all the hard work. 

## Setup

I've set up a repo to simulate my environment: https://gitlab.com/MigTex/ollama-helm#

As it is, without using gpu, the pod is created, all is ok

## Hardware

```
$ gpu-ls
Addon Package [clinfo] executable not found.  Use 'sudo apt install clinfo' to install
Detected GPUs: AMD: 1
AMD: amdgpu/rocm version: UNKNOWN
AMD: Wattman features not enabled: 0xfff7bfff, See README file.
Total of 1 GPU: 0 are rw, 1 is r-only, and 0 are w-only

Card Number: 0
   Vendor:  AMD 
   PP Features: high: 0x00003762 low: 0xa37f7dff
   Readable: True
   Writable: False
   Compute: Unknown
   GPU UID: c0d4390eac51b0b3
   Device ID: {'device': '0x73bf', 'subsystem_device': '0xe439', 'subsystem_vendor': '0x1da2', 'vendor': '0x1002'}
   Decoded Device ID: Navi 21 [Radeon RX 6800/6800 XT / 6900 XT]
   Card Model: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c3)
   Display Card Model:  Navi 21 RX
```

## Steps

set gpu.enabled to true

kubectl apply -f 

## Expected:
pod to start up 

## Actual: 
pod fails to start

Any advice is appreciated

### Chart version

1.7.0

### Kubernetes version

1.31.5

### Kubernetes distribution

k3s1

### Relevant log output

```shell
> stream closed EOF for ollama/ollama-helm-84f4dc8996-6pv45
```

### Your values.yaml

```yaml
image:
      repository: ollama/ollama
      tag: latest
      pullPolicy: IfNotPresent
    ollama:
      gpu:
        enabled: true
        type: 'amd'
      models:
        pull: [llama3.2]
        run: [llama3.2]
      mountPath: "$HOME/.local/share/ollama/models" # default is /root/.ollama
    service:
      type: NodePort # Changed from default ClusterIP
      port: 11434
      nodePort: 30434 # Added this line
    ingress:
      enabled: true
      hosts:
        - host: ollama.domain.lan
          paths:
            - path: /
              pathType: Prefix
      tls: []
    persistence:
      enabled: true
      size: 20Gi # Changed from default 10Gi
    resources:
      limits:
        cpu: 4
        memory: 16Gi # Changed from default 4Gi
      requests:
        cpu: 4
        memory: 8Gi
```

### Additional context

```markdown
https://gitlab.com/MigTex/ollama-helm#
```
