### ISSUE TITLE
Models are getting pulled during the helm upgrade

### ISSUE THREAD

**Issue by govindkailas** [otwld/ollama-helm#154]
### What happened?

I am using Ollama integrated with `open-webui`, I see that when I upgrade the helm chart, the models are getting pulled again regardless of their local existence. 

Reported here, https://github.com/open-webui/helm-charts/issues/193 
Have you ever come across something like this? 

### Chart version

0.5.12

### Kubernetes version

v1.32.0

### Kubernetes distribution

k8s

### Relevant log output

```shell

```

### Your values.yaml

```yaml
Relevant values for the model pull, 

  ollama:
    models:
      pull:
        - llama3.2
        - qwen2.5-coder
        - deepseek-r1
```

### Additional context

```markdown

```
