### ISSUE TITLE
Add Knative Service annotation configurability

### ISSUE THREAD

**Issue by dagasatvik10** [otwld/ollama-helm#160]
### Is your feature request related to a problem? Please describe

Currently, the Helm chart does not expose a way to customize annotations for the Knative Service template. Many critical Knative features (e.g., scaling behavior, pod retention, and concurrency) are controlled via annotations, such as:

- autoscaling.knative.dev/minScale
- autoscaling.knative.dev/maxScale
- autoscaling.knative.dev/scaleToZeroPodRetentionPeriod
- autoscaling.knative.dev/target

This feature would allow users to configure these annotations dynamically through values.yaml.

## Proposed solution
Add an annotations field to the Knative Service template in:

1. `values.yaml`
```yaml
knativeService:  
  annotations:  
    autoscaling.knative.dev/minScale: "1"  
    autoscaling.knative.dev/maxScale: "10"  
```
2. The Knative Service template (e.g., templates/knative-service.yaml):
```yaml
metadata:  
  annotations:  
    {{- toYaml .Values.knativeService.annotations | nindent 8 }}  
```

## Why this is useful

- Enables use of Knative’s scaling/autoscaling features.
- Allows optimization for cost (scale-to-zero) and performance (min/max replicas).
- Follows Helm best practices by making configurations declarative.

### Additional context

```markdown

```
