### ISSUE TITLE
Ollama service deployed in k8s pod, but web app can't communicate with the Ollama service

### ISSUE THREAD

**Issue by PrashantSaikia** [otwld/ollama-helm#23]
I am trying to deploy a chatbot UI that uses an LLM served with Ollama in the backend. Here are my steps to deploy the app in EKS Cluster:

### 1. Install Ollama using Helm

Create a file called `values.yaml` and save it with the following content:

```
ollama:
  gpu:
    # -- Enable GPU integration
    enabled: true
    
    # -- GPU type: 'nvidia' or 'amd'
    type: 'nvidia'
    
    # -- Specify the number of GPU to 2
    number: 1
   
  # -- List of models to pull at container startup
  models: 
    - kristada673/solar-10.7b-instruct-v1.0-uncensored
```

Then install the Ollama helm chart with `values.yaml` to say which model to load at the start:

`helm install ollama ollama-helm/ollama --values values.yaml --set model.name=kristada673/solar-10.7b-instruct-v1.0-uncensored`

### To check if Ollama is running:

I've verified that Ollama is running at `http://ollama:11434` using 4 different ways/methods:

#### A. Using Python:

```
kubectl exec -it $(kubectl get pods | awk '{print $1}' | grep web-app) -- python -c "import requests; print(requests.get('http://ollama:11434').text)"
>>> Ollama is running
```

#### B. Using interactive shell:

```
kubectl exec -it $(kubectl get pods | awk '{print $1}' | grep ollama) -- /bin/bash
ollama run kristada673/solar-10.7b-instruct-v1.0-uncensored
>>> hello
 Hello, how can I assist you today?
>>> 
```

#### C. Using temporary debugging pod to check if ollama is running
```
kubectl run tmp-debug --rm -it --image=busybox -- sh
wget -O- http://ollama:11434
>>> Connecting to ollama:11434 (<internal_cluster_IP>:11434)
writing to stdout
-  100% |*****************************************************************|    17  0:00:00 ETA
written to stdout
```

#### D. Using a curl shell
```
kubectl run curl -it --rm --image=curlimages/curl -- sh

curl http://ollama:11434/api/generate -d '{
  "model": "kristada673/solar-10.7b-instruct-v1.0-uncensored",
  "prompt": "Hello",
  "stream": false
}'

>>> {"model":"kristada673/solar-10.7b-instruct-v1.0-uncensored","created_at":"2024-04-14T21:17:24.361631356Z","response":" Hi, how can I assist you today?","done":true,"context":[774,2135,28747,995,460,264,10865,13892,28723,774,1247,28747,22557,774,21631,28747,15359,28725,910,541,315,6031,368,3154,28804],"total_duration":380529648,"load_duration":287930,"prompt_eval_count":4,"prompt_eval_duration":53166000,"eval_count":10,"eval_duration":326437000}
```

### 2. Here is the `app.py` file for the web app UI:

```
import gradio, os
from ollama import Client

model = 'kristada673/solar-10.7b-instruct-v1.0-uncensored'
OLLAMA_API_ENDPOINT = os.getenv('OLLAMA_API_ENDPOINT')

def format_history(msg: str, history: list[list[str, str]], system_prompt: str):
    system_prompt = "You are a helpful assistant and always try to answer user queries to the best of your ability."
    chat_history = [{"role": "system", "content":system_prompt}]
    for query, response in history:
        chat_history.append({"role": "user", "content": query})
        chat_history.append({"role": "assistant", "content": response})  
    chat_history.append({"role": "user", "content": msg})
    return chat_history

def generate_response(msg: str, history: list[list[str, str]], system_prompt: str):
    chat_history = format_history(msg, history, system_prompt)
    client = Client(host=OLLAMA_API_ENDPOINT)
    response = client.chat(model=model, stream=True, messages=chat_history)
    message = ""
    for partial_resp in response:
        token = partial_resp["message"]["content"]
        message += token

chatbot = gradio.ChatInterface(generate_response)
chatbot.queue().launch(server_name="0.0.0.0", server_port=8080)
```

Here's the `requirements.txt`:

```
gradio==4.25.0
ollama==0.1.8
```

And here's the `Dockerfile`:

```
FROM python:3.11-slim
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY . .
EXPOSE 8080
CMD ["python", "-u", "app.py"]
```

#### 3. Build a Docker Image of the Web App

1. **Create a Dockerfile** for the web app.
   
2. **Build the Docker image**.

`docker build -t yourusername/web-app:latest .`

3. **Push the Docker image** to a container registry accessible by the EKS cluster (e.g., Amazon ECR).

```
aws ecr get-login-password --region your-region | docker login --username AWS --password-stdin your-account-id.dkr.ecr.your-region.amazonaws.com
docker tag yourusername/web-app:latest your-account-id.dkr.ecr.your-region.amazonaws.com/yourusername/web-app:latest
docker push your-account-id.dkr.ecr.your-region.amazonaws.com/yourusername/web-app:latest
```

### 4. Deploy the Web App

Create the following kubernetes manifest called `web-app-deployment.yaml`:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: <aws_account_id>.dkr.ecr.eu-west-1.amazonaws.com/<cluster_name>:web-app-deployment-latest
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_API_ENDPOINT
          value: "http://ollama:11434"

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: web-app
```

#### Deploy the web app:

`kubectl apply -f web-app-deployment.yaml`

#### Verify the Deployment

Check the status of the deployment:

```
kubectl get deployments
kubectl get pods
```

### 5. Access the Web App

Once everything is deployed, the web application will be accessible through a LoadBalancer service, which assigns an external IP:

`kubectl get svc web-app-service`

Look for the `EXTERNAL-IP` of the `web-app-service`. This IP address can be used in the browser to access the web application:

<img width="1246" alt="Screenshot 2024-04-14 at 10 08 10 PM" src="https://github.com/otwld/ollama-helm/assets/39755678/c7e29272-12a1-432f-8f34-7f7433d78e83">

As you can see, there is no response from the LLM. So, I do:

`kubectl logs <name-of-the-web-app-deployment-pod>`

```
Running on local URL:  http://0.0.0.0:8080

WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
```

This tells me that the web app is not able to make API calls to Ollama.

When I do port forwarding to open the app in my local browser, it works:

`kubectl port-forward <name-of-the-web-app-deployment-pod> 8080:8080 --address 0.0.0.0`

<img width="1236" alt="Screenshot 2024-04-15 at 12 26 19 AM" src="https://github.com/otwld/ollama-helm/assets/39755678/ee3cb8bb-f9cd-4fc6-b55f-e0271ff3ce09">

So, what's going on? Is there anything missing in my steps?
