### ISSUE TITLE
exec /bin/ollama: exec format error

### ISSUE THREAD

**Issue by praveen-kanamarlapudi** [otwld/ollama-helm#26]
Hi,

Not sure if it's question to be asked here or ollama repo.

I am trying to run ollama (using GPU) on AWS EKS with Nvidia V100. When I use the official docker image, I am getting below error
```
exec /bin/ollama: exec format error
```

Anything I am doing wrong?

Also, I am using the below values
```
passing below values
ollama:
  gpu:
    enabled: true
    type: 'nvidia'
    number: 2
   
  # -- List of models to pull at container startup
  models: 
    - mistral

image:
  repository: ollama/ollama
  pullPolicy: IfNotPresent
  tag: "0.1.32" # I saw this is latest. I also tried with 0.1.31 with no luck
```

I also added necessary node selectors.

Appreciate any help
