### ISSUE TITLE
Support for Meta's LLAMA 3

### ISSUE THREAD

**Issue by ziadomalikold** [otwld/ollama-helm#27]
As you might know, LLAMA 3 released a while back. Is it already supported by ollama-helm? 
If not, what steps would I need to take to add support for it? Would be happy to contribute.

**Comment by jdetroyes** [comment]
Hello @ziadomalik ,

As @nhenderson said, you just need to add in your values.yaml the llama3 model or use the [REST API](https://github.com/ollama/ollama/blob/main/docs/api.md) to pull it.

```yaml
# Ollama parameters
ollama:
  models:
    - llama3
```
