### ISSUE TITLE
Hard coded volumeMounts section causes problems in Openshift

### ISSUE THREAD

**Issue by dboschbach-bw** [otwld/ollama-helm#65]
Hi,
depending on policy restrictions I have to patch this section of the helm chart or make my own helm chart when I want to deploy to Openshift.
```
volumeMounts:
  - name: ollama-data
    mountPath: /root/.ollama
```
https://github.com/otwld/ollama-helm/blob/main/templates/deployment.yaml#L89-L90

Can this be moved to the `values.yaml` or another separate volume section?

**Comment by ntrehout** [comment]
Thanks for reaching out!

You’re right, this should be configurable with the values.yaml. I'll make the modification ASAP (~48h).

Meanwhile, join our [Discord ](https://discord.gg/NcGncDxg) for real-time updates and help :)

**Comment by dboschbach-bw** [comment]
Here is the example I use. The route part is openshift specific. But that is not the problem I am talking about and isn't your problem to deal with.

`cat kustomization.yaml`

```
resources:
  - ../base
  - resource-route.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ollama
    path: patch-volume-mount.yaml
 ```
`patch-volume-mount.yaml`
```
- op: replace
  path: /spec/template/spec/containers/0/volumeMounts/0/mountPath
  value: /.ollama
```

`helm upgrade -i ollama ollama-helm/ollama -n <namespace> -f values.yaml --atomic --cleanup-on-fail --timeout 600s--post-renderer ./hook.sh`

```
#!/bin/bash
cat <&0 >./base/resources.yaml
oc kustomize ./openshift/
rm ./base/resources.yaml
```
