### ISSUE TITLE
Allow Setting hostIPC: true

### ISSUE THREAD

**Issue by emouawad** [otwld/ollama-helm#67]
ollama/ollama:latest
Back-off restarting failed container ollama
Deployed in GKE with nvidea with auto-driver install

Issue: Setting hostIPC=true in yaml deployment fixes the issue - following is a deployment test.yaml that works vs helm chart that can't set the flag

```shell
2024/07/13 18:45:42 routes.go:940: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MAX_VRAM:0 OLLAMA_MODELS:/root/.ollama/models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR: OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-07-13T18:45:42.101Z level=INFO source=images.go:760 msg="total blobs: 0"
time=2024-07-13T18:45:42.101Z level=INFO source=images.go:767 msg="total unused blobs removed: 0"
time=2024-07-13T18:45:42.101Z level=INFO source=routes.go:987 msg="Listening on [::]:11434 (version 0.2.3)"
time=2024-07-13T18:45:42.102Z level=INFO source=payload.go:30 msg="extracting embedded files" dir=/tmp/ollama3512381301/runners
time=2024-07-13T18:45:45.684Z level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cuda_v11 rocm_v60101 cpu cpu_avx cpu_avx2]"
time=2024-07-13T18:45:45.684Z level=INFO source=gpu.go:205 msg="looking for compatible GPUs"
SIGSEGV: segmentation violation
PC=0x7f7bf9e4b17a m=8 sigcode=1 addr=0x18
signal arrived during cgo execution

goroutine 1 gp=0xc0000061c0 m=8 mp=0xc0002d7808 [syscall]:
runtime.cgocall(0xf71ce0, 0xc000048770)
	runtime/cgocall.go:157 +0x4b fp=0xc000048748 sp=0xc000048710 pc=0x43544b
github.com/ollama/ollama/gpu._Cfunc_nvcuda_init(0x7f7c10000b70, 0xc000602800)
	_cgo_gotypes.go:535 +0x3f fp=0xc000048770 sp=0xc000048748 pc=0x8307df
github.com/ollama/ollama/gpu.LoadNVCUDAMgmt.func2(0x7f7c10000b70, 0xc000602800)
	github.com/ollama/ollama/gpu/gpu.go:548 +0x4a fp=0xc0000487a0 sp=0xc000048770 pc=0x836a2a
github.com/ollama/ollama/gpu.LoadNVCUDAMgmt({0xc000044e10, 0x1, 0x1e5b9640?})
	github.com/ollama/ollama/gpu/gpu.go:548 +0x13d fp=0xc000048958 sp=0xc0000487a0 pc=0x8363dd
github.com/ollama/ollama/gpu.initCudaHandles()
	github.com/ollama/ollama/gpu/gpu.go:122 +0x41f fp=0xc000048b38 sp=0xc000048958 pc=0x83135f
github.com/ollama/ollama/gpu.GetGPUInfo()
	github.com/ollama/ollama/gpu/gpu.go:238 +0x2f7 fp=0xc000049b30 sp=0xc000048b38 pc=0x831cf7
github.com/ollama/ollama/server.Serve({0x1de801f8, 0xc00049ae00})
	github.com/ollama/ollama/server/routes.go:1020 +0x7a5 fp=0xc000049cd0 sp=0xc000049b30 pc=0xf45385
github.com/ollama/ollama/cmd.RunServer(0xc0001cd200?, {0x1e7107c0?, 0x4?, 0x129cb5f?})
	github.com/ollama/ollama/cmd/cmd.go:1086 +0xfa fp=0xc000049d58 sp=0xc000049cd0 pc=0xf682ba
github.com/spf13/cobra.(*Command).execute(0xc0004e4308, {0x1e7107c0, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x882 fp=0xc000049e78 sp=0xc000049d58 pc=0x7c6042
github.com/spf13/cobra.(*Command).ExecuteC(0xc00047bb08)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5 fp=0xc000049f30 sp=0xc000049e78 pc=0x7c6885
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.7.0/command.go:985
main.main()
	github.com/ollama/ollama/main.go:11 +0x4d fp=0xc000049f50 sp=0xc000049f30 pc=0xf70d6d
runtime.main()
	runtime/proc.go:271 +0x29d fp=0xc000049fe0 sp=0xc000049f50 pc=0x46bdbd
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000049fe8 sp=0xc000049fe0 pc=0x49efe1
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: ollama
  template:
    metadata:
      labels:
        name: ollama
    spec:
      hostIPC: true
      nodeSelector:
        cloud.google.com/gke-gpu-sharing-strategy: mps
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama
      containers:
        - name: ollama
          image: ollama/ollama:latest
          env:
            - name: PATH
              value: /usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - name: LD_LIBRARY_PATH
              value: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: compute,utility
          ports:
            - name: http
              containerPort: 11434
              protocol: TCP

          resources:
            limits:
              nvidia.com/gpu: 1

          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama

          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6

          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 6

      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
```

Success Logs:

```shell
2024/07/13 18:57:50 routes.go:965: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MAX_VRAM:0 OLLAMA_MODELS:/root/.ollama/models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR: OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-07-13T18:57:50.945Z level=INFO source=images.go:760 msg="total blobs: 0"
time=2024-07-13T18:57:50.946Z level=INFO source=images.go:767 msg="total unused blobs removed: 0"
time=2024-07-13T18:57:50.946Z level=INFO source=routes.go:1012 msg="Listening on [::]:11434 (version 0.2.4)"
time=2024-07-13T18:57:50.946Z level=INFO source=payload.go:30 msg="extracting embedded files" dir=/tmp/ollama2667956584/runners
time=2024-07-13T18:57:54.663Z level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cpu_avx cpu_avx2 cuda_v11 rocm_v60101 cpu]"
time=2024-07-13T18:57:54.663Z level=INFO source=gpu.go:205 msg="looking for compatible GPUs"
time=2024-07-13T18:57:55.039Z level=INFO source=types.go:105 msg="inference compute" id=GPU-87a4628c-308b-d098-a574-39de810dc276 library=cuda compute=7.5 driver=12.2 name="Tesla T4" total="14.6 GiB" available="1.5 GiB"
```
