### ISSUE TITLE
All GPUs are used instead of single one when gpu.number=1

### ISSUE THREAD

**Issue by cgrozea** [otwld/ollama-helm#98]
### What happened?

All 8 GPUs in an 8 GPUs machine were seen by the pod - e.g. with nvidia-smi. 
Also, when used by multiple clients, it spawn ollama_llama_server processed in the pod, each on a different GPU.

*The way I fixed it for us:* commented out in templates/deployment.yaml this environment variable:
  - name: NVIDIA_VISIBLE_DEVICES
              value: all

After that, one still get in the environment variable NVIDIA_VISIBLE_DEVICES at runtime the 
NVIDIA_VISIBLE_DEVICES=GPU-{UUID}
and everything seems to work fine.

### Chart version

0.58.0

### Kubernetes version

1.29.1 on that node

### Kubernetes distribution

k8s

### Your values.yaml

```yaml
odeSelector:
  kubernetes.io/hostname: gep7
persistentVolume:
  enabled: true
  existingClaim: ollama-claim

resources:
  limits:
    nvidia.com/gpu: 1 # requesting 1 GPU 

ollama:
  gpu:
    # -- Enable GPU integration
    enabled: true
    
    # -- GPU type: 'nvidia' or 'amd'
    type: 'nvidia'
    
    # -- Specify the number of GPU to 1
    number: 1
   
  # -- List of models to pull at container startup
#  models: 
#    - mistral
#    - llama2
```

### Additional context

```markdown
As you can see I've tried to fix it with 
resources:
  limits:
    nvidia.com/gpu: 1 # requesting 1 GPU 
as well, but this had no effect before I eliminated NVIDIA_VISIBLE_DEVICES from the template
```

**Comment by jdetroyes** [comment]
Hello @cgrozea 

Thanks you for your catch.

We will remove these environment variables since they are already included in the [Dockerfile](https://github.com/ollama/ollama/blob/main/Dockerfile):
```yaml
            - name: PATH
              value: /usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - name: LD_LIBRARY_PATH
              value: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: compute,utility
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
```
